version: '3.8'

services:
  mpd:
    build:
      context: . # 指向 Dockerfile 所在的目录
      args:
        BUILD_UID: 1000
        BUILD_GID: 1000
    container_name: mpd_server
    #ports:
    #  - "6600:6600" # 如果您想从宿主机直接访问MPD端口
    volumes:
      - ./data/mpd:/var/lib/mpd # 持久化 MPD 数据
      - ./data/music:/var/lib/mpd/music:ro # 挂载音乐目录 (只读)
    restart: unless-stopped

  mympd:
    image: jcorporation/mympd:latest # 使用官方 myMPD Docker 镜像
    container_name: mympd_webui
    ports:
      - "8000:8000" # 映射 myMPD 的 Web UI 端口
    volumes:
      - ./data/mympd:/var/lib/mympd # 持久化 myMPD 的配置和数据
    environment:
      # 如果 myMPD 需要连接到 MPD 容器，需要设置 MPD_HOST
      # 这里使用 Docker Compose 的服务名称作为主机名
      MPD_HOST: mpd:6600 # myMPD 会通过这个地址连接到 MPD 容器
    restart: unless-stopped
    depends_on:
      - mpd # 确保 mympd 在 mpd 启动后才启动