
services:
  mpd:
    image: ${DOCKERHUB_USERNAME}/mpd-custom:latest
    container_name: mpd
    ports:
      - "6600:6600"
    volumes:
      - /path/to/your/music:/var/lib/mpd/music
      - /path/to/your/playlists:/var/lib/mpd/playlists
    environment:
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
    restart: unless-stopped

