# docker-compose.yml
version: '3.8'

services:
  mpd-gdocker:
    
    image: mpd-docker:main
    container_name: mpd-docker
    restart: unless-stopped
    ports:
      - "6600:6600" # 宿主机端口 6600 -> 容器端口 6600 (MPD 协议)
      - "8000:8000" # 宿主机端口 8000 -> 容器端口 8000 (ympd Web UI)

    volumes:
      - ./music:/var/lib/mpd/music:ro
      - ./config/mpd.conf:/etc/mpd/mpd.conf:ro
      - ./data/playlists:/var/lib/mpd/playlists
      - ./data/database:/var/lib/mpd/database
      - ./data/log:/var/lib/mpd/log
      - ./data/state:/var/lib/mpd/state
      - ./data/sticker:/var/lib/mpd/sticker

    # devices: # 如果需要访问宿主机音频设备
    #   - /dev/snd:/dev/snd